services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:dev
    container_name: aiostreams
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - ADDON_PROXY=${PROXY_URL:-}   # only route requests to any strem.fun subdomain through the proxy
      - ADDON_PROXY_CONFIG=*:false,*.strem.fun:true   # only route requests to any strem.fun subdomain through the proxy
      - EASYNEWS_PLUS_URL=${AIOSTREAMS_EASYNEWS_PLUS_URL:-}
      - MEDIAFUSION_URL=${AIOSTREAMS_MEDIAFUSION_URL:-}
      - MEDIAFUSION_API_PASSWORD=${MEDIAFUSION_API_PASSWORD:-}
      - MEDIAFUSION_CONFIG_TIMEOUT=3000
      - COMET_URL=${AIOSTREAMS_COMET_URL:-}
      - FORCE_COMET_HOSTNAME=${COMET_HOSTNAME:-}
      - COMET_INDEXERS=${COMET_INDEXERS:-}
      - JACKETTIO_URL=${AIOSTREAMS_JACKETTIO_URL:-}
      - STREMIO_JACKETT_URL=${AIOSTREAMS_STREMIO_JACKETT_URL:-}
      - JACKETT_URL=${AIOSTREAMS_JACKETT_URL:-}
      - JACKETT_API_KEY=${AIOSTREAMS_JACKETT_API_KEY:-}
      - JACKETT_INDEXERS=${AIOSTREAMS_JACKETT_INDEXERS:-}
      - SECRET_KEY=${AIOSTREAMS_SECRET_KEY} 
      - DEFAULT_TIMEOUT=5000
      - TMDB_API_KEY=${TMDB_API_KEY:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aio.rule=Host(`${AIOSTREAMS_HOSTNAME}`)"
      - "traefik.http.routers.aio.entrypoints=websecure"
      - "traefik.http.routers.aio.tls.certresolver=myresolver"
      - "flame.type=app"
      - "flame.name=AIOStreams"
      - "flame.url=https://${AIOSTREAMS_HOSTNAME}"
    networks:
      - addon_network

networks:
  addon_network:
    external: true