services:
  seanime:
    image: umagistr/seanime
    container_name: seanime
    command: 
    volumes:
      - /mnt/user/anime:/anime
      - /mnt/user/downloads:/downloads
      - ./data/seanime:/root/.config/Seanime
    expose:
      - 43211
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seanime.rule=Host(`${SEANIME_HOSTNAME}`)"
      - "traefik.http.routers.seanime.entrypoints=websecure"
      - "traefik.http.routers.seanime.tls.certresolver=myresolver"
      - "traefik.http.routers.seanime.middlewares=seanime-auth"
      - "traefik.http.middlewares.seanime-auth.basicauth.users=${SEANIME_USERNAME}:${SEANIME_HASHED_PASSWORD}"
      - "flame.type=app"
      - "flame.name=Seanime"
      - "flame.url=https://${SEANIME_HOSTNAME}"
    healthcheck:
      test: wget -qO- http://localhost:43211/api/v1/status
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - addon_network

networks:
  addon_network:
    external: true