services:
  mediafusion:
    image: mhdzumair/mediafusion:latest
    container_name: mediafusion
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - HOST_URL=https://${MEDIAFUSION_HOSTNAME}
      - POSTER_HOST_URL=https://${MEDIAFUSION_HOSTNAME}
      - MONGO_URI=mongodb://mongodb:27017/mediafusion
      - REDIS_URL=redis://redis:6379
      - IS_SCRAP_FROM_TORRENTIO=true
      - IS_SCRAP_FROM_MEDIAFUSION=true
      - IS_SCRAP_FROM_ZILEAN=true
      - IS_SCRAP_FROM_PROWLARR=true
      - IS_SCRAP_FROM_JACKETT=true
      - IS_SCRAP_FROM_YTS=false
      - PROWLARR_API_KEY=${PROWLARR_API_KEY:-}
      - PROWLARR_URL=http://prowlarr:9696
      - PROWLARR_IMMEDIATE_MAX_PROCESS=30
      - PROWLARR_IMMEDIATE_MAX_PROCESS_TIME=30
      - PROWLARR_SEARCH_INTERVAL_HOUR=24
      - PROWLARR_LIVE_TITLE_SEARCH=true
      - JACKETT_URL=http://jackett:9117
      - JACKETT_API_KEY=${JACKETT_API_KEY:-}
      - JACKETT_IMMEDIATE_MAX_PROCESS=30
      - JACKETT_IMMEDIATE_MAX_PROCESS_TIME=30
      - JACKETT_SEARCH_INTERVAL_HOUR=24
      - JACKETT_LIVE_TITLE_SEARCH=true
      - ENABLE_RATE_LIMIT=false
      - TORRENTIO_URL=https://torrentio.strem.fun
      - MEDIAFUSION_URL=https://mediafusion.elfhosted.com
      - ZILEAN_URL=http://zilean:8181
      - STORE_STREMTHRU_MAGNET_CACHE=false
      - REQUESTS_PROXY_URL=${HTTP_PROXY_URL:-}
      - FLARESOLVERR_URL=http://flaresolverr:8191
      - TMDB_API_KEY=${TMDB_API_KEY} # https://www.themoviedb.org/settings/api
      - SECRET_KEY=${MEDIAFUSION_SECRET_KEY}  # openssl rand -hex 32
      - API_PASSWORD=${MEDIAFUSION_API_PASSWORD} # random password for API
#     - LOGGING_LEVEL="DEBUG"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      warp:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediafusion.rule=Host(`${MEDIAFUSION_HOSTNAME}`)"
      - "traefik.http.routers.mediafusion.entrypoints=websecure"
      - "traefik.http.routers.mediafusion.tls.certresolver=myresolver"
      - "flame.type=app"
      - "flame.name=MediaFusion"
      - "flame.url=https://${MEDIAFUSION_HOSTNAME}"
    networks:
      - addon_network

networks:
  addon_network:
    external: true