services:
  aiostremio:
    image: viren070/aiostremio:latest
    container_name: aiostremio
    restart: unless-stopped
    expose:
      - 8469
    volumes:
     - ./data/aiostremio:/app/data
    environment:
      ADMIN_USERNAME: ${AIOSTREMIO_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${AIOSTREMIO_ADMIN_PASSWORD}
      MEDIAFLOW_API_PASSWORD: ${MEDIAFLOW_API_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      DEBRID_API_KEY: ${DEBRID_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiostremio.rule=Host(`${AIOSTREMIO_HOSTNAME}`)"
      - "traefik.http.routers.aiostremio.entrypoints=websecure"
      - "traefik.http.routers.aiostremio.tls.certresolver=myresolver"
      - "flame.type=app"
      - "flame.name=AIOStreams"
      - "flame.url=https://${AIOSTREMIO_HOSTNAME}"