services:
  realdebrid-account-monitor:
    build:
      context: .
    pull_policy: build
    image: realdebrid-account-monitor
    container_name: realdebrid-account-monitor
    env_file:
      - .env
    volumes:
      - ${DOCKER_DATA_DIR}/realdebrid-account-monitor:/app/data
    restart: unless-stopped
    profiles:
      - realdebrid-account-monitor


